version: '3.9'
services:
  api:
    container_name: nestJs-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    volumes:
      - ./apps/api/src:/app/apps/api/src
    networks:
      - test
    ports:
      - 3000:3000

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - test
    ports:
      - '5432:5432'

networks:
  test:
    name: test

volumes:
  postgres:
